---
namespace: stdevel
name: uyuni
version: 0.3.5
readme: README.md
authors:
  - Christian Stankowic <info@cstan.io>
description: Collection of modules to manage Uyuni / SUSE Manager
license:
  - GPL-3.0-only

tags:
  - infrastructure
  - eda
  - linux
  - systemsmanagement
  - uyuni
  - suse
  - manager

dependencies:
  "community.general": "*"
  "containers.podman": "*"

repository: https://github.com/stdevel/ansible-collection-uyuni
documentation: https://github.com/stdevel/ansible-collection-uyuni/blob/main/README.md
homepage: https://github.com/stdevel/ansible-collection-uyuni
issues: https://github.com/stdevel/ansible-collection-uyuni/issues
