---
- name: Ensure having proper architecture
  ansible.builtin.fail:
    msg: "SUSE MLM Proxy only supports x86_64 and aarch64"
  when:
    - ansible_architecture not in ['x86_64', 'aarch64']

- name: Ensure having SUSE MLM release equal/greater than 5.0
  ansible.builtin.fail:
    msg: "SUSE MLM releases older than 5.0 are unsupported"
  when:
    - proxy_suma_release is defined
    - "proxy_suma_release is version('5.0', '<')"

- name: Ensure having supported SP release for SUSE MLM 5.1
  ansible.builtin.fail:
    msg: "Please upgrade to SLES 15 SP7"
  when:
    - proxy_suma_release == 5.1
    - ansible_distribution_version != '15.7'

- name: Ensure having supported SP release for SUMA 5.0
  ansible.builtin.fail:
    msg: "SLES 15 is not supported for SUMA 5.0"
  when:
    - proxy_suma_release == 5.0
