---
- name: Ensure having proper architecture
  ansible.builtin.fail:
    msg: "SUSE MLM Proxy only supports x86_64 and aarch64"
  when:
    - ansible_architecture not in ['x86_64', 'aarch64']

- name: Ensure having SUSE MLM release equal/greater than 5.0
  ansible.builtin.fail:
    msg: "SUSE MLM releases older than 5.0 are unsupported"
  when:
    - proxy_suma_release is defined
    - "proxy_suma_release is version('5.0', '<')"

- name: Ensure having supported SL Micro release for SUSE MLM 5.1
  ansible.builtin.fail:
    msg: "Please upgrade to SL Micro 6.1"
  when:
    - proxy_suma_release == 5.1
    - ansible_distribution_version != '6.1'

- name: Ensure having supported SLE Micro release for SUMA 5.0
  ansible.builtin.fail:
    msg: "Please upgrade to SLE Micro 5.5"
  when:
    - proxy_suma_release == 5.0
    - ansible_distribution_version != '5.5'
