---
- name: Check CPU
  ansible.builtin.fail:
    msg: "Please ensure having at least 2 CPUs"
  when:
    - ansible_processor_vcpus < 2
    - proxy_check_requirements

- name: Check memory
  ansible.builtin.fail:
    msg: "Please ensure having at least 8 GB of memory"
  when:
    - ansible_memtotal_mb < 7900
    - proxy_check_requirements
