---
- name: Converge machines
  hosts: all
  become: true
  pre_tasks:
    - name: Set hostname
      block:
        - name: Set (short) hostname
          ansible.builtin.hostname:
            name: uyuni

        - name: Update /etc/hosts
          ansible.builtin.lineinfile:
            path: /etc/hosts
            regexp: '^127.0.0.1'
            line: '127.0.0.1 localhost uyuni.vagrant.loc uyuni'

    - name: Remove package manager locks (required for Vagrantbox)
      ansible.builtin.command: zypper rl "{{ item }}"
      register: zypper_out
      changed_when: "'successfully removed' in zypper_out.stdout"
      loop:
        - snapper
        - snapper-zypp-plugin

    - name: Install required packages
      community.general.zypper:
        name:
          - snapper
          - snapper-zypp-plugin

  roles:
    - role: server
      uyuni_cefs_setup: true
      uyuni_cefs_setup_cronjob: true
      uyuni_channels:
        - name: centos7
          arch: x86_64
        - name: centos7-updates
          arch: x86_64
      uyuni_enable_monitoring: true
      uyuni_install_monitoring_formulas: true
      # uyuni_release: '2023.03'
      uyuni_firewall_config: true
