---
uyuni_repo_file: /etc/apt/sources.list.d/susemanager:channels.list

uyuni_client_packages:
  - venv-salt-minion
uyuni_minion_service: venv-salt-minion
uyuni_client_directories:
  - /etc/venv-salt-minion
  - /var/cache/venv-salt-minion
