---
uyuni_pattern:
  - patterns-uyuni_server

uyuni_repos:
  - url: "https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable/images/repo/Uyuni-Server-POOL-{{ ansible_architecture }}-Media1"
    name: uyuni-server-stable
  - url: "https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/Patches/openSUSE_Leap_{{ ansible_distribution_version }}/"
    name: uyuni-server-patches

uyuni_repo_release:
  - url: "https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Snapshots:/{{ uyuni_release }}/images/"
    name: uyuni-server-stable
  - url: "https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/Patches/openSUSE_Leap_{{ ansible_distribution_version }}/"
    name: uyuni-server-patches

uyuni_firewall_services:
  - suse-manager-server
uyuni_firewall_ports: []
