---
- name: Ensure having Leap Micro release 5.5
  ansible.builtin.fail:
    msg: "Please ensure having release 5.5"
  when:
    - "ansible_distribution_version != '5.5'"

- name: Ensure having Uyuni release equal/greater than 2024.03
  ansible.builtin.fail:
    msg: "Uyuni releases older than 2024.03 are unsupported - use an older version of this collection"
  when:
    - uyuni_release is defined
    - "uyuni_release is version('2024.03', '<=')"
