---
- name: Install requirements
  community.general.zypper:
    name: "{{ uyuni_cefs_packages }}"
    state: present
  become: true
  when: uyuni_cefs_setup

- name: Install errata-import
  become: true
  when: uyuni_cefs_setup
  block:
    - name: Create folder
      ansible.builtin.file:
        path: "{{ uyuni_cefs_path }}"
        state: directory
        owner: root
        group: root
        mode: 0755
    - name: Download errata-import
      ansible.builtin.get_url:
        url: https://github.com/stevemeier/cefs/raw/master/errata-import.pl
        dest: "{{ uyuni_cefs_path }}/errata-import.pl"
        mode: "0755"
    - name: Install wrapper script
      ansible.builtin.template:
        src: errata-import.sh.j2
        dest: "{{ uyuni_cefs_path }}/wrapper.sh"
        mode: "0755"
        owner: root
        group: root

- name: Install CEFS cronjob
  ansible.builtin.cron:
    name: "Import CentOS errata"
    job: "{{ uyuni_cefs_path }}/wrapper.sh cefs"
    user: root
    cron_file: "errata-cefs"
    special_time: daily
  become: true
  when: uyuni_cefs_setup_cronjob | bool

- name: Create software channels
  ansible.builtin.command: spacewalk-common-channels -u {{ uyuni_org_login }} -p {{ uyuni_org_password }} -a {{ item.arch }} {{ item.name }}
  loop: "{{ uyuni_channels }}"
  register: create_result
  changed_when:
    - '"exists" not in create_result.stdout | lower'
    - '"already in use" not in create_result.stderr | lower'
  become: true
  when: uyuni_channels | length > 0

- name: Get software channels
  ansible.builtin.command: spacecmd -q -u {{ uyuni_org_login }} -p {{ uyuni_org_password }} softwarechannel_list
  changed_when: false
  register: software_channels
  when: uyuni_sync_channels | bool

- name: Sync software channels
  ansible.builtin.command: spacewalk-repo-sync -c {{ item }}
  loop: "{{ software_channels.stdout.split('\n')  }}"
  become: true
  when: uyuni_sync_channels | bool

- name: Get bootstrap distributions
  ansible.builtin.command: mgr-create-bootstrap-repo -l
  changed_when: false
  register: bootstrap_distributions
  become: true
  when: uyuni_bootstrap_repos | bool

- name: Create bootstrap repositories
  ansible.builtin.command: "mgr-create-bootstrap-repo -f -c {{ item | regex_replace('^[0-9].', '') }}"
  loop: "{{ bootstrap_distributions.stdout.split('\n') }}"
  become: true
  when: uyuni_bootstrap_repos | bool
