---
- name: Install Uyuni pattern
  community.general.zypper:
    name: "{{ uyuni_pattern }}"
  become: true

- name: Install tools
  community.general.zypper:
    name: "{{ uyuni_packages }}"
  become: true

- name: Stage deploy configuration
  ansible.builtin.template:
    src: setup_env.sh.j2
    dest: "/root/setup_env.sh"
    mode: "0755"
    owner: root
    group: root
  become: true

- name: Initialize database
  ansible.builtin.command: /usr/lib/susemanager/bin/mgr-setup -s
  args:
    creates: /root/.MANAGER_SETUP_COMPLETE
  become: true

- name: Wait for web server to come up
  ansible.builtin.wait_for:
    port: 80
    delay: 20

- name: Create initial organization and user
  ansible.builtin.uri:
    url: https://localhost/rhn/newlogin/CreateFirstUser.do
    method: POST
    validate_certs: false
    body: "submitted=true&orgName={{ uyuni_org_name }}&login={{ uyuni_org_login }}&desiredpassword={{ uyuni_org_password }}&desiredpasswordConfirm={{ uyuni_org_password }}&email={{ uyuni_org_mail }}&firstNames={{ uyuni_org_first_name }}&lastName={{ uyuni_org_last_name }}"   # noqa: 204
    body_format: "form-urlencoded"
    status_code:
      - 201
      - 302
    creates: /root/.MANAGER_INITIALIZATION_COMPLETE
  become: true
  register: org_created

- name: Create initialization file
  ansible.builtin.file:
    path: /root/.MANAGER_INITIALIZATION_COMPLETE
    owner: root
    group: root
    mode: '0644'
    state: touch
  become: true
  when: org_created.status is defined and org_created.status in [201, 302]
