---
- name: Add release GPG keys
  ansible.builtin.rpm_key:
    key: "{{ item }}"
  loop: "{{ uyuni_repo_gpg }}"
  become: true
  when: uyuni_release is defined

- name: Add latest GPG keys
  ansible.builtin.rpm_key:
    key: "{{ item }}"
  loop: "{{ uyuni_gpg }}"
  become: true
  when: uyuni_release is undefined

- name: Add release Uyuni repositories
  community.general.zypper_repository:
    repo: "{{ item.url }}"
    name: "{{ item.name }}"
  loop: "{{ uyuni_repo_release }}"
  become: true
  when:
    - uyuni_use_repo | bool
    - uyuni_release is defined

- name: Add latest Uyuni repositories
  community.general.zypper_repository:
    repo: "{{ item.url }}"
    name: "{{ item.name }}"
  loop: "{{ uyuni_repos }}"
  become: true
  when:
    - uyuni_use_repo | bool
    - uyuni_release is undefined

- name: Add Perl repositories (openSUSE Leap 15.4)
  community.general.zypper_repository:
    repo: https://download.opensuse.org/repositories/devel:languages:perl/15.4/devel:languages:perl.repo
  when:
    - uyuni_cefs_setup
    - "ansible_distribution_version == '15.4'"
  become: true


  # Disable patch repos as long as no patch repo for 15.5 exists
- name: Disable Patch Repo for openSUSE 15.5 as long no patch is available
  community.general.zypper_repository:
    repo: "https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/Patches/openSUSE_Leap_{{ ansible_distribution_version }}/"
    name: uyuni-server-patches
    enabled: False
  when:
    - "ansible_distribution_version == '15.5'"
  become: true
