---
- name: Add release GPG keys
  ansible.builtin.command: "transactional-update --continue run rpm --import {{ item }}"
  loop: "{{ uyuni_gpg }}"
  notify: Reboot system
  become: true

- name: Add release Uyuni repositories
  ansible.builtin.command: "transactional-update --continue run zypper ar {{ item.url }}"
  loop: "{{ uyuni_repos }}"
  notify: Reboot system
  become: true

- name: Set default image name
  ansible.builtin.set_fact:
    uyuni_image_name: registry.opensuse.org/uyuni/server
  when: uyuni_release is not defined

- name: Set default image name (release-specific)
  ansible.builtin.set_fact:
    uyuni_image_name: "registry.opensuse.org/systemsmanagement/uyuni/snapshots/{{ uyuni_release }}/containers/uyuni/server"
  when: uyuni_release is defined
